### ISSUE TITLE
current_user.is_authenticated returns false in deployment

### ISSUE THREAD

**Issue by max454545** [RafaelMiquelino/dash-flask-login#5] opened 2020-06-04 07:39 UTC
Hello,

Thanks for making this repository.

I have been using it with success on a localhost, but as soon as I deploy it, on a hosted server, the user authentication stops behaving.  As the user logs in, it registers that the user is authenticated, but within less than a 1s the bool current_user.is_authenticated is set to false.

I have tried everything, and this problem is consistent for my code, that includes the code from this repository, and if one puts this repository on a server and runs it.

Thanks and all the best,
Max H

**Comment by RafaelMiquelino** [comment] 2020-06-04 10:33
Hi Max,

Are you sure your code is not triggering the `logout_user()` function anywhere? I’ve never seen this behavior before, so you may want to investigate further your code but feel free to share more details so we can find a solution for that if this is related to the code in this repository. Also I assume you are not using the flask internal server for your solution right? I don’t think this is related but that is something I never tried at a production server.

________________________________

**Comment by max454545** [comment] 2020-06-04 12:09
Hello Rafael,
Thanks for getting back so quickly.

I changed your code by adding the following line to app.py:

app = app.server

I made the above change in order to use the flask internal server.  Is this the wrong approach?

The gif below shows the behavior on a local server (browser on the left), vs the behavior on a hosted server (browser window on the right).

![gif_github](https://user-images.githubusercontent.com/66354962/83754922-0d1ef480-a66d-11ea-9664-54084a3eedba.gif)

**Comment by RafaelMiquelino** [comment] 2020-06-04 12:20
> I changed your code by adding the following line to app.py:
> 
> app = app.server
> 
> I made the above change in order to use the flask internal server. Is this where I am going wrong?

You shouldn’t need to do that, just run `flask run --host=0.0.0.0` and your app you’ll be served externally. However I recommended you use gunicorn, the Flask internal server is not suitable for production environment. Take a look here for an example on how to serve the app with gunicorn: https://github.com/RafaelMiquelino/flask-text-reader/blob/master/README.md#instructions.

**Comment by max454545** [comment] 2020-06-04 12:26
I have tried gunicorn on a Heroku server (still with the line 'server = app.server') and the problem persisted.  

I will try flask run --host=0.0.0.0 and get back to you.

Thank you again

**Comment by max454545** [comment] 2020-06-05 07:22
I am truly stuck.  
Our preferred host uses passenger as the  application server.  The only way that I can think of making the passenger_wsgi.py file is by adding the line 'server = app.server' to app.y, which is the incorrect way to do it.  

Do you know how I could make the passenger_wsgi.py file to correctly run 
dash-flask-login, without altering app.py?

**Comment by max454545** [comment] 2020-06-05 14:56
I see that dash-auth-flow is also nolonger working in production.  Is it possible that Flask login is no longer a viable option for Dash apps?

Here is there app, it exhibits the same faulty behavior as dash-flask-login on my server:
http://dash-auth-flow.herokuapp.com/login

**Comment by lapshinmr** [comment] 2020-06-05 19:22
Hey. Please, take a look at these pages: [issue133](https://github.com/plotly/dash/issues/133) and https://dash.plotly.com/urls. It looks like your problem not in the login feature but in the multi-page rendering.

**Comment by RafaelMiquelino** [comment] 2020-06-06 12:28
@max454545 , I just made some tests and deployed it to Heroku and it behaves like expected, i.e.: I couldn't reproduce your issue. I added the instructions to run it with gunicorn and deploy to Heroku on the README. If you follow this instructions you'll be able to do that too.
I have a working example on the link https://dash-flask-login-rm.herokuapp.com that you can check by yourself. You'll probably need to investigate deeper your code and please share here when you managed to solve it.

**Comment by RafaelMiquelino** [comment] 2020-06-06 12:36
Actually, I checked it again and it indeed behaves in a strange manner. Maybe there is something to do what @lapshinmr just mentioned.

**Comment by RafaelMiquelino** [comment] 2020-06-06 13:05
So I forced gunicorn to use only one worker when running on Heroku: https://github.com/RafaelMiquelino/dash-flask-login/blob/master/Procfile#L1.
It is working now but it is more a workaround than a solution. It seems the issue is really related to the mentioned above by @lapshinmr. The Dash maintainer says it is solved from the version 0.11.0 but we are using the version 1.4.1 here and the issue is still there, so it needs to be further investigated.
@max454545, you should probably work on a more robust solution for your case and if you find, please share it here. For the moment I'm closing this issue as this is not related to the login process but to the multi-page rendering process.

**Closed by RafaelMiquelino** 2020-06-06 13:05 UTC

**Comment by RafaelMiquelino** [comment] 2020-06-06 13:27
Another possibility that appears to solve this same issue: https://github.com/RafaelMiquelino/dash-flask-login/issues/2

**Comment by max454545** [comment] 2020-06-09 07:13
Thanks Mr lapshinmr  and RafaelMiquelino for looking into the issue, I appreciate it.

github.com/russellromney seems to have encountered the same problem and found a solution:
https://github.com/russellromney/dash-auth-flow/issues/2
